In [128]:
from google.cloud import bigquery

In [236]:
import pandas as pd
path = '/Users/bernardoaraujo/code/bchojniak/filmaholic/raw_data/ml-25m'
movies_df = pd.read_csv(path + '/' + 'movies.csv',dtype='str')
ratings_df = pd.read_csv(path + '/' + 'ratings.csv',dtype='str').iloc[:500000, :]
tags_df = pd.read_csv(path + '/' + 'tags.csv',dtype='str')
links_df = pd.read_csv(path + '/' + 'links.csv',dtype='str')
genome_tags_df = pd.read_csv(path + '/' + 'genome-tags.csv',dtype='str')
genome_scores_df = pd.read_csv(path + '/' + 'genome-scores.csv',dtype='str')

In [155]:
len(links_df)

62423

In [76]:
imdb_id = links_df['imdbId'].sample()
imdb_id = imdb_id.values[0]
url = (f'https://www.imdb.com/title/tt{imdb_id}')
print(url)

https://www.imdb.com/title/tt3799996

In [77]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
HEADERS = {'User-Agent': 'Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148'}

response = requests.get(url,headers=HEADERS)
soup = BeautifulSoup(response.content, "html.parser")

In [78]:
# sample_size = 10

# def generate_random_imdb_id():
#     return str(links_df['imdbId'].sample().values[0])

# def imdb_list(sample_size):
#     imdb_id_list = [generate_random_imdb_id() for _ in range(sample_size)]
#     return imdb_id_list
# imdb_list(sample_size)

['0020876',
 '5364518',
 '2978716',
 '1277146',
 '1794801',
 '4691804',
 '0360130',
 '0056713',
 '7429362',
 '0057372']

# Features Scraped

## Release Date

In [79]:
def date_search(imdb_id):
    url = (f'https://www.imdb.com/title/tt{imdb_id}')
    response = requests.get(url, headers=HEADERS)
    soup = BeautifulSoup(response.content, "html.parser")
    
    search_list = soup.find_all("a", class_ = "ipc-metadata-list-item__list-content-item ipc-metadata-list-item__list-content-item--link")
    
    for date in search_list:
        if 'releaseinfo' in date['href']:
            return date.text
date_search(imdb_id)

'November 27, 2014 (Australia)'

## Country of Origin

In [80]:
def country_search(imdb_id):
    url = (f'https://www.imdb.com/title/tt{imdb_id}')
    response = requests.get(url, headers=HEADERS)
    soup = BeautifulSoup(response.content, "html.parser")
    
    search_list = soup.find_all("a", class_ = "ipc-metadata-list-item__list-content-item ipc-metadata-list-item__list-content-item--link")
    
    for country in search_list:
        if 'country_of_origin' in country['href']:
            return country.text
country_search(imdb_id)

'Australia'

## Movie Duration

In [81]:
# imdb_id = links_df['imdbId'].sample()
# imdb_id = imdb_id.values[0]
# duration_url = (f'https://www.imdb.com/title/tt{imdb_id}/technical')

# response = requests.get(duration_url,headers=HEADERS)
# duration_soup = BeautifulSoup(response.content, "html.parser")

'''Have a better look at this'''

'Have a better look at this'

In [82]:
def movie_duration(imdb_id):    
    url = (f'https://www.imdb.com/title/tt{imdb_id}')
    response = requests.get(url, headers=HEADERS)
    soup = BeautifulSoup(response.content, "html.parser")
    
    search_duration = soup.find_all("li", class_ = "ipc-metadata-list__item")
    
    for search in search_duration:
        if 'data-testid' in search.attrs and 'title-techspec_runtime' in search['data-testid']:
            duration = search.text.strip()
            duration = duration.replace("Runtime", "").strip()
            return duration
movie_duration(imdb_id)

'1 hour 39 minutes'

## Director

In [83]:
crew_url = (f'https://www.imdb.com/title/tt{imdb_id}/fullcredits')

response1 = requests.get(crew_url,headers=HEADERS)
crew_soup = BeautifulSoup(response1.content, "html.parser")

print(crew_url)

https://www.imdb.com/title/tt3799996/fullcredits

In [84]:
def director_search(imdb_id):
    url = f'https://www.imdb.com/title/tt{imdb_id}/fullcredits'
    response = requests.get(url, headers=HEADERS)
    crew_soup = BeautifulSoup(response.content, "html.parser")
    
    table_direct = crew_soup.find("table", class_ = "simpleTable simpleCreditsTable")
    
    for table in range(len(table_direct)):
        if table == 1:
            director = crew_soup.find("td", class_ = "name")
            director = director.text.replace("\n","")
            return director

director_search(imdb_id)

' Paul Fenech '

## Actors

In [113]:
def actors_search(imdb_id):
    crew_url = f'https://www.imdb.com/title/tt{imdb_id}/fullcredits'
    response = requests.get(crew_url, headers=HEADERS)
    crew_soup = BeautifulSoup(response.content, "html.parser")
    
    table_act = crew_soup.find("table", class_="cast_list")
    
    mt = []
    for ppl in table_act:
        ppl = ppl.text.replace("\n", "").strip()
        mt.append(ppl)
    
    actors = []
    for actor in mt:
        actor_name = ""
        for c in range(len(actor)):
            if actor[c] == '.':
                actor_name = actor[:c].strip()
                break
        if actor_name:
            actors.append(actor_name)
    actors = actors[:3]
    return actors
actors_search(imdb_id)

['Paul Fenech', 'Elle Dawe', 'Kevin Taumata']

## Music by

In [114]:
table_music = crew_soup.find_all("table", class_ = "simpleTable simpleCreditsTable")

# for music in table_music:
#     print(music.text)
#     print("\n")
    
# for music in range(len(table_music)):
#     if music == 2:
#         musician = crew_soup.find("td", class_ = "name")
#         print(musician.text)

# Function

In [156]:
%%time
import requests
from bs4 import BeautifulSoup
import pandas as pd

sample_size = 1000

def generate_random_imdb_id():
    return str(links_df['imdbId'].sample().values[0])


def imdb_list(sample_size):
    imdb_id_list = [generate_random_imdb_id() for _ in range(sample_size)]
    return imdb_id_list

def features_scraped():
    id_list = imdb_list(sample_size)
    print(id_list)
    
    data_list = []
    error_list = []
    working_id_list = []
    for id in id_list:
        try:
            release = date_search(id)
            origin = country_search(id)
            movie_length = movie_duration(id)
            director_name = director_search(id)
            actors_names = actors_search(id)
            actor_1,actor_2,actor_3 = actors_names[0],actors_names[1],actors_names[2]
            
            data_list.append([release, origin, movie_length, director_name, actor_1,actor_2,actor_3])
            
            working_id_list.append(id)
        except:
            print(id)
            error_list.append(id)
            
    print(working_id_list)   
    columns = ['Release_Date', 'Country_of_Origin', 'Movie_Length', 'Director', 'Actor_1','Actor_2','Actor_3']
    scraped_df = pd.DataFrame(data=data_list, columns=columns, index =working_id_list)
    scraped_df = scraped_df.reset_index().rename(columns = {'index':'IMDBid'})
        
    return (scraped_df, error_list)

result, errors = features_scraped()
result

['0120381', '5208950', '2364841', '2854926', '4397382', '0041788', '3917908', '0049470', '7460806', '1555803', '0079702', '0477302', '4240654', '3563782', '0088170', '5526028', '1685576', '0109934', '0257044', '0092809', '2980794', '0436078', '1155053', '0068327', '1073131', '7319496', '2641152', '0397363', '0048248', '8305116', '1464251', '0119517', '2130282', '4920274', '0076119', '0806006', '0086148', '9308454', '0031442', '0092632', '0116046', '0037335', '3521442', '2343707', '0211359', '0019992', '0104509', '0098353', '0364930', '1830792', '0103003', '6762430', '0397078', '0117395', '0197857', '0067333', '0082602', '0078865', '0040587', '1865364', '0058025', '0338556', '0047435', '1978567', '0243278', '0377701', '0093215', '0365677', '1323973', '0079553', '0059014', '0407936', '0062271', '0051136', '0383694', '1846783', '0120744', '0871426', '0306016', '0352696', '0095993', '7128732', '1591622', '2746176', '0373889', '1282024', '0116992', '2980684', '1667353', '0104030', '2008633', '4061944', '4446472', '1074638', '0066040', '3107070', '0044070', '8025310', '0198769', '0266408', '5599692', '0310000', '0075082', '4535788', '0343112', '3775086', '0890882', '0044386', '0203725', '0372122', '5672048', '0044622', '0038279', '0284061', '0948544', '1670715', '1609807', '1235536', '0102365', '0030746', '5345298', '0079679', '0053274', '2901516', '0069080', '5473090', '0084395', '0284714', '0119986', '1301160', '0064893', '1787777', '6209470', '1780945', '1667130', '0092669', '5275866', '1270494', '0301244', '0485241', '2701390', '3560546', '1087873', '0245501', '0092210', '2962876', '2493466', '1094162', '0045706', '1194236', '0068339', '1249294', '1810683', '0459913', '2475544', '0267536', '0024960', '0326963', '0059243', '0067345', '6492186', '0066302', '2368833', '0032490', '0068658', '0036566', '0030293', '0108473', '0071378', '0159057', '3907584', '2992000', '0061473', '0443844', '0299594', '0111756', '0086992', '0862667', '6964562', '0102779', '0294940', '0129767', '5068280', '1806910', '0081748', '1594918', '0923954', '0090474', '0058461', '0047960', '9563632', '0068179', '0046754', '0303162', '1172995', '0080700', '2354141', '0447619', '0337996', '0928154', '0037749', '0119141', '1292575', '4559046', '0072701', '1692214', '1667889', '0069006', '6878820', '0091508', '0156770', '3169780', '0031966', '0105046', '0102397', '1830238', '6929642', '3620298', '0023790', '0284139', '0358947', '2400275', '2765306', '2670830', '7923170', '1810833', '0416938', '0120654', '0089598', '0080827', '0069228', '2091473', '0028653', '0368619', '0059741', '0015167', '0065750', '6892340', '0896815', '0787500', '0052644', '0074852', '0070782', '2202473', '0338216', '0049518', '5225874', '0414413', '0449181', '0103295', '0027196', '0238936', '0103045', '0082121', '0077192', '0249691', '0086434', '0032746', '3347994', '7213936', '6136188', '2128693', '7016254', '0258827', '3881784', '0093603', '0044357', '2241750', '0116393', '0218864', '0094025', '0362387', '0076276', '1632481', '0110091', '0070244', '5276332', '0023846', '5456798', '3322940', '3130594', '0077222', '0197626', '0027212', '0117422', '9099102', '1999167', '0091869', '0121431', '3951298', '2057392', '1210351', '0975684', '0058920', '0105885', '0031777', '3905764', '2241083', '1564367', '0026983', '0216216', '0390632', '0171587', '0212408', '0028852', '1329454', '0065193', '0302274', '0058949', '0065595', '0095832', '3453648', '0105428', '5644006', '0346513', '3319844', '1094627', '0106758', '0040577', '1378702', '0133906', '1798181', '6742252', '0458481', '0051090', '0020563', '0073036', '0059692', '3786680', '0022289', '0174480', '1756595', '0284978', '1753846', '0118804', '0050259', '0145893', '0428430', '0186910', '0080084', '0039829', '0455612', '0038417', '3667152', '0097221', '0158117', '0327210', '0071492', '1450321', '0213446', '10039344', '0106536', '3737280', '2036388', '0666194', '0073841', '0111751', '1034303', '0054325', '0984118', '0047203', '0287092', '0106678', '0120202', '1823672', '0062385', '0181359', '0065581', '0082121', '5112578', '6195442', '0020891', '0017423', '3733606', '0066140', '0483812', '0450314', '3268790', '0370053', '0094667', '0106521', '0285052', '1772256', '0304584', '2109208', '0075221', '0021664', '0047370', '5314190', '3892434', '5563334', '1158939', '0086590', '0144106', '0090719', '1563738', '0070078', '0229533', '0449018', '0821638', '0953458', '2540072', '9598172', '1847584', '2217936', '4477536', '0088952', '0199013', '0024302', '2101341', '0031972', '2705402', '0172495', '0098488', '2396566', '0102007', '0881909', '0041871', '1183374', '0130208', '0059425', '0034012', '0075723', '0162926', '0167147', '1942900', '1920846', '0016630', '0477851', '1276121', '1640220', '0353393', '0072123', '7675404', '0050458', '0080179', '0080850', '3148552', '0036975', '4900708', '2622122', '0103327', '0824091', '0059555', '1874789', '0026748', '2452200', '4799066', '4145108', '1708133', '1704147', '1172203', '4494718', '3228302', '3484796', '1013752', '0047120', '3589968', '0255873', '1291150', '0028225', '1451618', '0078870', '0252866', '0070926', '0022504', '6241872', '2066048', '3528498', '3321470', '0406222', '0057532', '0079509', '0234215', '0372237', '0082853', '2577876', '0070140', '0040849', '3061222', '0036933', '6121428', '0224317', '8611750', '0308476', '1213663', '1288411', '0144546', '9471730', '3261114', '0088961', '0059389', '1337589', '2065015', '0145394', '1667108', '2402085', '0057193', '1667353', '2570858', '3516158', '0123368', '0066929', '0062722', '1828976', '0068772', '1587807', '6186430', '0111640', '0474694', '3103318', '0395121', '4606514', '0975673', '0062753', '0361240', '1259528', '0222512', '1434925', '4991112', '0089665', '5133288', '0461872', '2366572', '0933382', '0048990', '2586070', '0464665', '0067729', '0273719', '1205541', '0760188', '2657138', '0385703', '4714568', '7620554', '0463373', '7555072', '6574240', '0028767', '1616096', '2077005', '1397280', '0042393', '0016630', '0272020', '0934320', '0085416', '1077262', '0032390', '0332285', '0891562', '4246758', '1834303', '0070235', '0065962', '4328992', '0643103', '8305690', '0111800', '2429640', '0098244', '4046784', '5652620', '0077549', '0042849', '0456047', '2547172', '7736212', '2091288', '3108244', '1567247', '3398052', '0118674', '1511425', '1029120', '4854126', '0070698', '0077360', '0457270', '0056963', '0046908', '0043000', '2387543', '7332306', '0081157', '0395796', '0266437', '0470752', '0066289', '0315110', '0094946', '0374569', '1648035', '0048260', '0083891', '0075987', '0410407', '7748426', '2994832', '0063569', '0085313', '0092626', '4465220', '0364569', '0068657', '1070820', '7938444', '0280453', '4057438', '0424774', '0479537', '0150216', '0400420', '0319343', '1340795', '1338558', '2654562', '0025829', '3185602', '4476106', '5843056', '0301777', '0065380', '4057632', '0067329', '2182169', '7639372', '0120786', '0051454', '0119038', '0454776', '0203082', '0023926', '0000565', '3120408', '1467273', '0804550', '0021505', '0106586', '0914797', '5847286', '3606838', '1450334', '2289920', '1356392', '0084965', '3381610', '0403539', '4177972', '0091653', '0094320', '0419773', '0088885', '5210380', '0437029', '0374102', '0058648', '1806913', '3823690', '0083144', '1333631', '2403883', '2223820', '0038774', '0031593', '0079912', '3565066', '0264464', '0888817', '0955298', '5120400', '0052638', '0462322', '0050233', '0100506', '1536048', '4699464', '0362864', '0121989', '5985052', '7715070', '0090738', '1592525', '0356680', '0027527', '0097021', '0040418', '0312409', '0048500', '0103767', '0055740', '0188453', '0834899', '0273646', '1411238', '0441627', '1367454', '1719497', '0192470', '0083367', '0053571', '0076551', '3286560', '5179576', '0060635', '0078277', '0105265', '0072813', '0092028', '6892340', '0343135', '1206543', '6063648', '0058333', '5622284', '0120458', '1235535', '8111210', '0022685', '4308590', '3653518', '4835636', '1792799', '0109001', '0029171', '0051051', '0080002', '2342227', '0018839', '2721744', '3220528', '0029009', '1334272', '0093258', '1243955', '1536537', '0357058', '0104361', '3455830', '3562572', '1500761', '1702009', '0098206', '5589750', '3074694', '0078474', '0457414', '0200049', '4936450', '1242527', '5451244', '2272350', '0135427', '7293380', '0800135', '0077800', '0053740', '0018051', '0072783', '0022059', '0889212', '0765469', '0039294', '1563719', '0228457', '0063486', '2023690', '0473434', '0785532', '0337697', '0109446', '0037711', '0364961', '0096046', '0061981', '0060089', '0132347', '0053825', '1634300', '0468529', '0054403', '5339432', '6210160', '0003740', '0068941', '0083335', '0095175', '0486636', '9033632', '3250032', '6343314', '0417385', '0039689', '0094841', '0095869', '4505170', '1763288', '1645131', '0037098', '0395495', '0045926', '0037101', '1278293', '3506934', '0085547', '5848714', '0078843', '0222299', '3147312', '1506452', '0066540', '4978274', '0133689', '1607577', '0476991', '0126604', '0078539', '0093952', '0059199', '4228816', '0022471', '0046986', '0091957', '4439120', '0084388', '1740545', '0087571', '0087489', '0039080', '0070714', '0150211', '1827579', '0092003', '0383222', '2035670', '0068184', '7064498', '1756640', '0756725', '0043465', '0018397', '2464486', '0052393', '2934272', '0134862', '0327733', '0099136', '1599378', '0971170', '1503770', '0040875', '0036940', '0325596', '5690360', '1186366', '1187064', '0073906', '0093964', '2724532', '0476958', '0081245', '1320378', '6418778', '0960731', '1240899', '0045758', '2224075', '0101244', '1326954', '0181536', '0075045', '7000942', '0410377', '0113115', '0043338', '7410684', '3569014', '0052182', '0056060', '4363984', '0034078', '3591696', '1754570', '0109678', '1754560', '2936180', '4420946', '0095396', '0340468', '0053214', '0885520', '0024219', '1442571', '1667307', '0425061', '0071644', '0472156', '2234550', '4161520', '7476946', '0043067', '6332764', '7026370', '3530146', '0052293', '8119752', '0059337', '1019402', '0118607', '0101627', '0242445', '2554812', '0056052', '0100827', '0021217', '0119838', '0366544', '5182856', '1087578', '1493246', '0065031', '0043970', '0218266', '1078931', '0114683', '0070326', '3121200', '1179069', '0226199', '1959332', '0053800', '0223509', '0163651', '2120844', '0107501', '0096833', '1211837', '0030896', '0188797', '0086148', '0111507', '0075665', '0123755', '5729870', '0119687', '0100762', '0071695', '0815181', '2633666', '2484460', '2363309', '0039195', '0056657', '0112634', '0125879', '6086096', '0070111', '4084060', '0048680', '4123430', '0437029', '3642618', '6293032', '6926356', '0062863', '0110690', '0164114', '4365518', '0066485', '4289340', '6937878', '7046524', '0322802', '4161520', '1193490', '1487906', '1714828', '0093589', '0080966', '0240944', '0036711', '0103917', '1846492', '0089907', '0120271', '0133751', '3585116', '0023042', '0064111', '3455730', '0037569', '0087803', '0050097', '0310851', '1427241', '0110893', '0142239', '7227742', '1653827']

3563782
2641152
3521442
0117395
0040587
0058025
4535788
0343112
0284061
0294940
1172995
0156770
1830238
0284139
0358947
2765306
7923170
0059741
0449181
0249691
3347994
2128693
0171587
0302274
1378702
1798181
0666194
0073841
0953458
0199013
0881909
0026748
3228302
3528498
0224317
2065015
0145394
1587807
3103318
0975673
4991112
1205541
5652620
0046908
0315110
4057438
0000565
3823690
0103767
0273646
1367454
1235535
4835636
0109001
0104361
1500761
1740545
1756640
2464486
1320378
7410684
3569014
0056060
4363984
7026370
0223509
2484460
6086096
0037569
1653827
['0120381', '5208950', '2364841', '2854926', '4397382', '0041788', '3917908', '0049470', '7460806', '1555803', '0079702', '0477302', '4240654', '0088170', '5526028', '1685576', '0109934', '0257044', '0092809', '2980794', '0436078', '1155053', '0068327', '1073131', '7319496', '0397363', '0048248', '8305116', '1464251', '0119517', '2130282', '4920274', '0076119', '0806006', '0086148', '9308454', '0031442', '0092632', '0116046', '0037335', '2343707', '0211359', '0019992', '0104509', '0098353', '0364930', '1830792', '0103003', '6762430', '0397078', '0197857', '0067333', '0082602', '0078865', '1865364', '0338556', '0047435', '1978567', '0243278', '0377701', '0093215', '0365677', '1323973', '0079553', '0059014', '0407936', '0062271', '0051136', '0383694', '1846783', '0120744', '0871426', '0306016', '0352696', '0095993', '7128732', '1591622', '2746176', '0373889', '1282024', '0116992', '2980684', '1667353', '0104030', '2008633', '4061944', '4446472', '1074638', '0066040', '3107070', '0044070', '8025310', '0198769', '0266408', '5599692', '0310000', '0075082', '3775086', '0890882', '0044386', '0203725', '0372122', '5672048', '0044622', '0038279', '0948544', '1670715', '1609807', '1235536', '0102365', '0030746', '5345298', '0079679', '0053274', '2901516', '0069080', '5473090', '0084395', '0284714', '0119986', '1301160', '0064893', '1787777', '6209470', '1780945', '1667130', '0092669', '5275866', '1270494', '0301244', '0485241', '2701390', '3560546', '1087873', '0245501', '0092210', '2962876', '2493466', '1094162', '0045706', '1194236', '0068339', '1249294', '1810683', '0459913', '2475544', '0267536', '0024960', '0326963', '0059243', '0067345', '6492186', '0066302', '2368833', '0032490', '0068658', '0036566', '0030293', '0108473', '0071378', '0159057', '3907584', '2992000', '0061473', '0443844', '0299594', '0111756', '0086992', '0862667', '6964562', '0102779', '0129767', '5068280', '1806910', '0081748', '1594918', '0923954', '0090474', '0058461', '0047960', '9563632', '0068179', '0046754', '0303162', '0080700', '2354141', '0447619', '0337996', '0928154', '0037749', '0119141', '1292575', '4559046', '0072701', '1692214', '1667889', '0069006', '6878820', '0091508', '3169780', '0031966', '0105046', '0102397', '6929642', '3620298', '0023790', '2400275', '2670830', '1810833', '0416938', '0120654', '0089598', '0080827', '0069228', '2091473', '0028653', '0368619', '0015167', '0065750', '6892340', '0896815', '0787500', '0052644', '0074852', '0070782', '2202473', '0338216', '0049518', '5225874', '0414413', '0103295', '0027196', '0238936', '0103045', '0082121', '0077192', '0086434', '0032746', '7213936', '6136188', '7016254', '0258827', '3881784', '0093603', '0044357', '2241750', '0116393', '0218864', '0094025', '0362387', '0076276', '1632481', '0110091', '0070244', '5276332', '0023846', '5456798', '3322940', '3130594', '0077222', '0197626', '0027212', '0117422', '9099102', '1999167', '0091869', '0121431', '3951298', '2057392', '1210351', '0975684', '0058920', '0105885', '0031777', '3905764', '2241083', '1564367', '0026983', '0216216', '0390632', '0212408', '0028852', '1329454', '0065193', '0058949', '0065595', '0095832', '3453648', '0105428', '5644006', '0346513', '3319844', '1094627', '0106758', '0040577', '0133906', '6742252', '0458481', '0051090', '0020563', '0073036', '0059692', '3786680', '0022289', '0174480', '1756595', '0284978', '1753846', '0118804', '0050259', '0145893', '0428430', '0186910', '0080084', '0039829', '0455612', '0038417', '3667152', '0097221', '0158117', '0327210', '0071492', '1450321', '0213446', '10039344', '0106536', '3737280', '2036388', '0111751', '1034303', '0054325', '0984118', '0047203', '0287092', '0106678', '0120202', '1823672', '0062385', '0181359', '0065581', '0082121', '5112578', '6195442', '0020891', '0017423', '3733606', '0066140', '0483812', '0450314', '3268790', '0370053', '0094667', '0106521', '0285052', '1772256', '0304584', '2109208', '0075221', '0021664', '0047370', '5314190', '3892434', '5563334', '1158939', '0086590', '0144106', '0090719', '1563738', '0070078', '0229533', '0449018', '0821638', '2540072', '9598172', '1847584', '2217936', '4477536', '0088952', '0024302', '2101341', '0031972', '2705402', '0172495', '0098488', '2396566', '0102007', '0041871', '1183374', '0130208', '0059425', '0034012', '0075723', '0162926', '0167147', '1942900', '1920846', '0016630', '0477851', '1276121', '1640220', '0353393', '0072123', '7675404', '0050458', '0080179', '0080850', '3148552', '0036975', '4900708', '2622122', '0103327', '0824091', '0059555', '1874789', '2452200', '4799066', '4145108', '1708133', '1704147', '1172203', '4494718', '3484796', '1013752', '0047120', '3589968', '0255873', '1291150', '0028225', '1451618', '0078870', '0252866', '0070926', '0022504', '6241872', '2066048', '3321470', '0406222', '0057532', '0079509', '0234215', '0372237', '0082853', '2577876', '0070140', '0040849', '3061222', '0036933', '6121428', '8611750', '0308476', '1213663', '1288411', '0144546', '9471730', '3261114', '0088961', '0059389', '1337589', '1667108', '2402085', '0057193', '1667353', '2570858', '3516158', '0123368', '0066929', '0062722', '1828976', '0068772', '6186430', '0111640', '0474694', '0395121', '4606514', '0062753', '0361240', '1259528', '0222512', '1434925', '0089665', '5133288', '0461872', '2366572', '0933382', '0048990', '2586070', '0464665', '0067729', '0273719', '0760188', '2657138', '0385703', '4714568', '7620554', '0463373', '7555072', '6574240', '0028767', '1616096', '2077005', '1397280', '0042393', '0016630', '0272020', '0934320', '0085416', '1077262', '0032390', '0332285', '0891562', '4246758', '1834303', '0070235', '0065962', '4328992', '0643103', '8305690', '0111800', '2429640', '0098244', '4046784', '0077549', '0042849', '0456047', '2547172', '7736212', '2091288', '3108244', '1567247', '3398052', '0118674', '1511425', '1029120', '4854126', '0070698', '0077360', '0457270', '0056963', '0043000', '2387543', '7332306', '0081157', '0395796', '0266437', '0470752', '0066289', '0094946', '0374569', '1648035', '0048260', '0083891', '0075987', '0410407', '7748426', '2994832', '0063569', '0085313', '0092626', '4465220', '0364569', '0068657', '1070820', '7938444', '0280453', '0424774', '0479537', '0150216', '0400420', '0319343', '1340795', '1338558', '2654562', '0025829', '3185602', '4476106', '5843056', '0301777', '0065380', '4057632', '0067329', '2182169', '7639372', '0120786', '0051454', '0119038', '0454776', '0203082', '0023926', '3120408', '1467273', '0804550', '0021505', '0106586', '0914797', '5847286', '3606838', '1450334', '2289920', '1356392', '0084965', '3381610', '0403539', '4177972', '0091653', '0094320', '0419773', '0088885', '5210380', '0437029', '0374102', '0058648', '1806913', '0083144', '1333631', '2403883', '2223820', '0038774', '0031593', '0079912', '3565066', '0264464', '0888817', '0955298', '5120400', '0052638', '0462322', '0050233', '0100506', '1536048', '4699464', '0362864', '0121989', '5985052', '7715070', '0090738', '1592525', '0356680', '0027527', '0097021', '0040418', '0312409', '0048500', '0055740', '0188453', '0834899', '1411238', '0441627', '1719497', '0192470', '0083367', '0053571', '0076551', '3286560', '5179576', '0060635', '0078277', '0105265', '0072813', '0092028', '6892340', '0343135', '1206543', '6063648', '0058333', '5622284', '0120458', '8111210', '0022685', '4308590', '3653518', '1792799', '0029171', '0051051', '0080002', '2342227', '0018839', '2721744', '3220528', '0029009', '1334272', '0093258', '1243955', '1536537', '0357058', '3455830', '3562572', '1702009', '0098206', '5589750', '3074694', '0078474', '0457414', '0200049', '4936450', '1242527', '5451244', '2272350', '0135427', '7293380', '0800135', '0077800', '0053740', '0018051', '0072783', '0022059', '0889212', '0765469', '0039294', '1563719', '0228457', '0063486', '2023690', '0473434', '0785532', '0337697', '0109446', '0037711', '0364961', '0096046', '0061981', '0060089', '0132347', '0053825', '1634300', '0468529', '0054403', '5339432', '6210160', '0003740', '0068941', '0083335', '0095175', '0486636', '9033632', '3250032', '6343314', '0417385', '0039689', '0094841', '0095869', '4505170', '1763288', '1645131', '0037098', '0395495', '0045926', '0037101', '1278293', '3506934', '0085547', '5848714', '0078843', '0222299', '3147312', '1506452', '0066540', '4978274', '0133689', '1607577', '0476991', '0126604', '0078539', '0093952', '0059199', '4228816', '0022471', '0046986', '0091957', '4439120', '0084388', '0087571', '0087489', '0039080', '0070714', '0150211', '1827579', '0092003', '0383222', '2035670', '0068184', '7064498', '0756725', '0043465', '0018397', '0052393', '2934272', '0134862', '0327733', '0099136', '1599378', '0971170', '1503770', '0040875', '0036940', '0325596', '5690360', '1186366', '1187064', '0073906', '0093964', '2724532', '0476958', '0081245', '6418778', '0960731', '1240899', '0045758', '2224075', '0101244', '1326954', '0181536', '0075045', '7000942', '0410377', '0113115', '0043338', '0052182', '0034078', '3591696', '1754570', '0109678', '1754560', '2936180', '4420946', '0095396', '0340468', '0053214', '0885520', '0024219', '1442571', '1667307', '0425061', '0071644', '0472156', '2234550', '4161520', '7476946', '0043067', '6332764', '3530146', '0052293', '8119752', '0059337', '1019402', '0118607', '0101627', '0242445', '2554812', '0056052', '0100827', '0021217', '0119838', '0366544', '5182856', '1087578', '1493246', '0065031', '0043970', '0218266', '1078931', '0114683', '0070326', '3121200', '1179069', '0226199', '1959332', '0053800', '0163651', '2120844', '0107501', '0096833', '1211837', '0030896', '0188797', '0086148', '0111507', '0075665', '0123755', '5729870', '0119687', '0100762', '0071695', '0815181', '2633666', '2363309', '0039195', '0056657', '0112634', '0125879', '0070111', '4084060', '0048680', '4123430', '0437029', '3642618', '6293032', '6926356', '0062863', '0110690', '0164114', '4365518', '0066485', '4289340', '6937878', '7046524', '0322802', '4161520', '1193490', '1487906', '1714828', '0093589', '0080966', '0240944', '0036711', '0103917', '1846492', '0089907', '0120271', '0133751', '3585116', '0023042', '0064111', '3455730', '0087803', '0050097', '0310851', '1427241', '0110893', '0142239', '7227742']
CPU times: user 23min 52s, sys: 1min 15s, total: 25min 8s
Wall time: 2h 14min 45s

,IMDBid,Release_Date,Country_of_Origin,Movie_Length,Director,Actor_1,Actor_2,Actor_3
0,0120381,"February 17, 1999 (Argentina)",United States,1 hour 32 minutes,Catherine Cyran,Kirsten Dunst,Zachery Ty Bryan,August Schellenberg
1,5208950,"January 26, 2018 (Poland)",United States,1 hour 50 minutes,Dimitri Logothetis,Alain Moussi,Sara Malakul Lane,Maxime Savaria
2,2364841,"October 4, 2013 (Brazil)",United States,1 hour 28 minutes,Brad Furman,Justin Timberlake,Ben Affleck,Gemma Arterton
3,2854926,"August 23, 2018 (Brazil)",United States,1 hour 40 minutes,Jeff Tomsic,Ed Helms,Lil Rel Howery,Jon Hamm
4,4397382,"October 16, 2015 (Sweden)",Sweden,1 hour 11 minutes,Pontus Klänge,Amanda Pajus,Lukas Holgersson,Tomas Norström
...,...,...,...,...,...,...,...,...
925,0310851,2002 (Canada),Canada,1 hour 30 minutes,Rodney Gibbons,Matt Frewer,Kenneth Welsh,Shawn Lawrence
926,1427241,"May 23, 2009 (Japan)",Japan,1 hour 58 minutes,Jun'ichi Mori,Ryo Kase,Masaki Okada,Fumiyo Kohinata
927,0110893,"June 1, 1994 (Czech Republic)",Czech Republic,1 hour 39 minutes,Zdenek Troska,Radek Valenta,Andrea Cerná,Yvetta Blanarovicová
928,0142239,"March 12, 1994 (Japan)",Japan,48 minutes,Shigeyasu Yamauchi,Masako Nozawa,Mayumi Tanaka,Takeshi Kusao
929,7227742,"July 17, 2017 (United States)",United States,1 hour 56 minutes,Derek Scott,Murda Pain,Lance Whittighton,Sino

In [157]:
result

,IMDBid,Release_Date,Country_of_Origin,Movie_Length,Director,Actor_1,Actor_2,Actor_3
0,0120381,"February 17, 1999 (Argentina)",United States,1 hour 32 minutes,Catherine Cyran,Kirsten Dunst,Zachery Ty Bryan,August Schellenberg
1,5208950,"January 26, 2018 (Poland)",United States,1 hour 50 minutes,Dimitri Logothetis,Alain Moussi,Sara Malakul Lane,Maxime Savaria
2,2364841,"October 4, 2013 (Brazil)",United States,1 hour 28 minutes,Brad Furman,Justin Timberlake,Ben Affleck,Gemma Arterton
3,2854926,"August 23, 2018 (Brazil)",United States,1 hour 40 minutes,Jeff Tomsic,Ed Helms,Lil Rel Howery,Jon Hamm
4,4397382,"October 16, 2015 (Sweden)",Sweden,1 hour 11 minutes,Pontus Klänge,Amanda Pajus,Lukas Holgersson,Tomas Norström
...,...,...,...,...,...,...,...,...
925,0310851,2002 (Canada),Canada,1 hour 30 minutes,Rodney Gibbons,Matt Frewer,Kenneth Welsh,Shawn Lawrence
926,1427241,"May 23, 2009 (Japan)",Japan,1 hour 58 minutes,Jun'ichi Mori,Ryo Kase,Masaki Okada,Fumiyo Kohinata
927,0110893,"June 1, 1994 (Czech Republic)",Czech Republic,1 hour 39 minutes,Zdenek Troska,Radek Valenta,Andrea Cerná,Yvetta Blanarovicová
928,0142239,"March 12, 1994 (Japan)",Japan,48 minutes,Shigeyasu Yamauchi,Masako Nozawa,Mayumi Tanaka,Takeshi Kusao
929,7227742,"July 17, 2017 (United States)",United States,1 hour 56 minutes,Derek Scott,Murda Pain,Lance Whittighton,Sino

In [158]:
PROJECT = "filmaholic-398017"
DATASET = "filmaholic"
TABLES = "scraped-features"

t = f"{PROJECT}.{DATASET}.{TABLES}"
    
client = bigquery.Client()
    
write_mode = "WRITE_TRUNCATE"
job_config = bigquery.LoadJobConfig(write_disposition=write_mode)
    
job = client.load_table_from_dataframe(result, t, job_config=job_config)
upload_scraped = job.result()

In [168]:
result.Director.head()

0        Catherine Cyran
1     Dimitri Logothetis
2            Brad Furman
3            Jeff Tomsic
4          Pontus Klänge
Name: Director, dtype: object

In [227]:
directors_list = list(set(result.Director))

vectorized_directors = {}
vector_counter = 0
    
for director in directors_list:
    vectorized_directors[director] = vector_counter
    vector_counter += 1
    
print(vectorized_directors)

{' Roger Corman ': 0, ' Aleksandr Itygilov ': 1, ' Ugo Liberatore ': 2, ' Andrzej Bartkowiak ': 3, ' Robert Dornhelm ': 4, ' Drew Hall ': 5, ' Till Schauder ': 6, ' Doug Pray ': 7, ' Boaz Davidson ': 8, ' Johannes Wahlström ': 9, ' Barbara Wong Chun-Chun ': 10, ' Charles Barton ': 11, ' Yôjirô Takita ': 12, ' Stanley Kramer ': 13, ' Steve Loter ': 14, ' Robert Gaffney ': 15, ' Gianfranco Parolini ': 16, ' Jirô Nagae ': 17, ' José María Zabalza ': 18, ' Matt Chung-tien Wu ': 19, ' Adrián Cardona ': 20, ' Kalidas ': 21, ' Jackie Kong ': 22, ' Tassos Boulmetis ': 23, ' Nancy Criss ': 24, ' John Trent ': 25, ' Donald Cammell ': 26, ' Tim Robbins ': 27, ' Kheiron ': 28, ' Zubin Sarosh ': 29, ' Louis Morneau ': 30, ' Henry Levin ': 31, ' Gavin Hood ': 32, ' Madonna ': 33, ' Reshef Levi ': 34, ' Edward Buzzell ': 35, ' Sabine Bernardi ': 36, ' André Hunebelle ': 37, ' John Hamburg ': 38, ' Scott Derrickson ': 39, ' Geoff Burrowes ': 40, ' Masato Harada ': 41, ' Iain Morris ': 42, ' Terry O. Morse ': 43, ' David Oelhoffen ': 44, ' Stuart McDonald ': 45, ' Mark Tarlov ': 46, ' Samira Goetschel ': 47, ' Brian Herzlinger ': 48, ' Masahiko Murata ': 49, ' Marlen Khutsiev ': 50, ' Greg Pak ': 51, ' Lyubov Lvova ': 52, ' Todd Portugal ': 53, ' Piero Cristofani ': 54, ' Shigeyasu Yamauchi ': 55, ' Zdenek Troska ': 56, ' Ha Yoo ': 57, ' Joseph Pevney ': 58, ' Julia Hart ': 59, ' Naomi Kawase ': 60, ' Lucio Fulci ': 61, ' Stanley Kubrick ': 62, ' Dave Alan Johnson ': 63, ' Bob Giordano ': 64, ' María Luisa Bemberg ': 65, ' Richard Rosson ': 66, ' Václav Havel ': 67, ' Andy Tennant ': 68, ' David Hemmings ': 69, ' Nathan Frankowski ': 70, ' Curtis Bernhardt ': 71, ' Dante Desarthe ': 72, ' Patryk Vega ': 73, ' Yves Simoneau ': 74, ' Gautham Vasudev Menon ': 75, ' Roberto Faenza ': 76, ' Sofia Coppola ': 77, ' Peter Foott ': 78, ' Nadav Lapid ': 79, ' David Mickey Evans ': 80, ' Robert Shallcross ': 81, ' Ramón Barea ': 82, ' Phil Wurtzel ': 83, ' John Schlesinger ': 84, ' Jean Delannoy ': 85, ' Seung-wan Ryu ': 86, ' Jonathan Miller ': 87, ' Yen-Ping Chu ': 88, ' Daniel DiMarco ': 89, ' Lina Wertmüller ': 90, ' Richard Dale ': 91, ' Toby Keeler ': 92, ' Hark Tsui ': 93, ' Michael Powell ': 94, ' Aleksey Balabanov ': 95, ' Jeremy Saville ': 96, ' Martha Coolidge ': 97, ' Nick Hamm ': 98, ' Caspian Tredwell-Owen ': 99, ' William Wyler ': 100, ' F.J. Ossang ': 101, ' Scott Z. Burns ': 102, ' Frank Miller ': 103, ' Mark Lund ': 104, ' Dianah Wynter ': 105, ' Alex Merkin ': 106, ' Edward Zwick ': 107, ' Habib Faisal ': 108, ' Roy Del Ruth ': 109, ' Niels Mueller ': 110, ' Alain Corneau ': 111, ' Reginald Le Borg ': 112, ' Tatyana Lioznova ': 113, ' Matti Grönberg ': 114, ' Mark Pellington ': 115, ' Kevin Phillips ': 116, ' Takehiko Shinjô ': 117, ' Sajid ': 118, ' George C. Wolfe ': 119, ' Peter Becker ': 120, ' Ki-hyeong Park ': 121, ' Jack Conway ': 122, ' Kazuhiro Furuhashi ': 123, ' Alfred Hitchcock ': 124, ' David Keith ': 125, ' Milind Ukey ': 126, ' Pantelis Voulgaris ': 127, ' Lana Wachowski ': 128, ' Tony Gatlif ': 129, ' Tim Connery ': 130, ' Francis Veber ': 131, ' Neal E. Fischer ': 132, ' Bouli Lanners ': 133, ' Julius Avery ': 134, ' Sergei Dvortsevoy ': 135, ' Mike Leigh ': 136, ' Taylor Wong ': 137, ' Margarethe von Trotta ': 138, ' Nikolai Ekk ': 139, ' Christian Gudegast ': 140, ' Tripp Reed ': 141, ' Herman Wuyts ': 142, ' Andrzej Jakimowski ': 143, ' William R. Kowalchuk Jr. ': 144, ' Steven Spielberg ': 145, ' Catherine Cyran ': 146, ' Lewis Gilbert ': 147, ' Scott Cooper ': 148, ' Bill Duke ': 149, ' Chuck Powers ': 150, ' Joel Schumacher ': 151, ' Sidney J. Furie ': 152, ' Hrishikesh Mukherjee ': 153, ' Mariano Peralta ': 154, ' Ashutosh Gowariker ': 155, ' Peter Segal ': 156, ' Gabe Klinger ': 157, ' Aleksey Batalov ': 158, ' Jean-Luc Godard ': 159, ' Hayato Kawai ': 160, ' Andrew Gosling ': 161, ' J.R. Bookwalter ': 162, ' Måns Mårlind ': 163, ' J. Lee Thompson ': 164, ' Tusi Tamasese ': 165, ' Aleksandr Rogozhkin ': 166, ' Steven Lisberger ': 167, ' Yukihiko Tsutsumi ': 168, ' John Landis ': 169, ' Pa. Ranjith ': 170, ' Jen Soska ': 171, ' Craig Anderson ': 172, ' Vardit Bilu ': 173, ' Aleksey Korenev ': 174, ' John Frankenheimer ': 175, ' Oliver Dieckmann ': 176, ' Laurent Tirard ': 177, ' Sean Garland ': 178, ' Clifton Ko ': 179, ' Johnnie To ': 180, ' Jean Becker ': 181, ' Tomas Villum Jensen ': 182, ' King Hu ': 183, ' Marianne Elliott ': 184, ' Marcell Jankovics ': 185, ' Richard Fleischer ': 186, ' Peter Medak ': 187, ' Peter Gantzler ': 188, ' Leslie Goodwins ': 189, ' Bertrand Arthuys ': 190, ' Ludwig Berger ': 191, ' Mauro Bolognini ': 192, ' Marek Piwowski ': 193, ' Laurent Herbiet ': 194, ' Carolina Jabor ': 195, ' George Cukor ': 196, ' Nick Broomfield ': 197, ' Pinchas Perry ': 198, ' Paulo Caldas ': 199, ' Michael Radford ': 200, ' Erik Poppe ': 201, ' Ana Kokkinos ': 202, ' Brett Haley ': 203, ' Byron Haskin ': 204, ' Adolfo Aristarain ': 205, ' Ken Annakin ': 206, ' Santiago Otheguy ': 207, ' Dario Argento ': 208, ' Krzysztof Zanussi ': 209, ' Ally Walker ': 210, ' Javier Aguirre ': 211, ' Nicholaus Goossen ': 212, ' Slobodan Sijan ': 213, ' Derek Cole ': 214, ' Monthon Arayangkoon ': 215, ' David Lowery ': 216, ' Sergio Martino ': 217, ' Bob Saget ': 218, ' Liz Marshall ': 219, ' Andrew Rossi ': 220, ' Norman Jewison ': 221, ' Jack Hively ': 222, ' Chris Kentis ': 223, ' Derek Scott ': 224, ' Catherine Breillat ': 225, ' Ivan Kavanagh ': 226, ' Peter Hewitt ': 227, ' Sion Sono ': 228, ' Iram Haq ': 229, ' Tay Garnett ': 230, ' Michael Miller ': 231, ' Gianni Martucci ': 232, ' Leonardo Benvenuti ': 233, ' Lucas Pavetto ': 234, " Robert Vincent O'Neil ": 235, ' Frank Borzage ': 236, ' Jean Yarbrough ': 237, ' Dorota Kedzierzawska ': 238, ' Glenn Casale ': 239, ' Craig McCall ': 240, ' Márta Mészáros ': 241, ' Steve Jodrell ': 242, ' David Lewis ': 243, ' Stanley Donen ': 244, ' James Toback ': 245, ' Tinto Brass ': 246, ' David Von Ancken ': 247, ' Vladimir Feoktistov ': 248, ' John Bruno ': 249, ' Gabriele Mainetti ': 250, ' Rafael Romero Marchent ': 251, ' Oz Scott ': 252, ' Josef von Sternberg ': 253, ' Rodney Gibbons ': 254, ' Larry Peerce ': 255, ' Harry Beaumont ': 256, ' Alberto De Martino ': 257, ' Ted Wilde ': 258, ' Luca Miniero ': 259, ' Terra Shin ': 260, ' Mat Whitecross ': 261, ' Martin Ritt ': 262, ' Gregory Marquette ': 263, ' Robert Florey ': 264, ' James Quinn ': 265, ' Victor Saville ': 266, ' Olya Zueva ': 267, ' Tomás Vorel ': 268, ' Nigel Cole ': 269, " Jun'ichi Mori ": 270, ' Shôko Nakamura ': 271, ' Lone Scherfig ': 272, ' Christopher Smith ': 273, ' Billy Wilder ': 274, ' Kurt Hoffmann ': 275, ' Ken Loach ': 276, ' Raoul Walsh ': 277, ' James Huth ': 278, ' Peter Rodger ': 279, ' Kôji Fukada ': 280, ' Michael Goguen ': 281, ' Damon Gameau ': 282, ' Jun Lana ': 283, ' Paul Auster ': 284, ' John Milius ': 285, ' John Schultz ': 286, ' Aaron Harvey ': 287, ' Omar Mullick ': 288, ' Justin Bare ': 289, ' Tom Gustafson ': 290, ' Ben Smallbone ': 291, ' Isao Yukisada ': 292, ' Leonard Nimoy ': 293, ' Bryce Clark ': 294, ' Jon S. Baird ': 295, ' Tom Jenkinson ': 296, ' Robert Pouret ': 297, ' Paul Mariano ': 298, ' Cris Silvent ': 299, ' Archie Mayo ': 300, ' Philippe Harel ': 301, ' Chia-Liang Liu ': 302, ' John Gilling ': 303, ' Rick Harper ': 304, ' Jonathan Liebesman ': 305, ' Sidney Lumet ': 306, ' Gualtiero Jacopetti ': 307, ' Carles Torrens ': 308, ' Brian De Palma ': 309, ' Sean Penn ': 310, ' Edward Dmytryk ': 311, ' Daniel Cockburn ': 312, ' David Yates ': 313, ' Noel Langley ': 314, ' Jack Smight ': 315, ' Allan Ungar ': 316, ' Dean Francis ': 317, ' Zbynek Brynych ': 318, ' Steven Caple Jr. ': 319, ' Chung Ting ': 320, ' Hilary Brougher ': 321, ' Norman McLaren ': 322, ' Kim Kyung-mook ': 323, ' Jennifer Flackett ': 324, ' David Michael Conley ': 325, ' Albertina Carri ': 326, ' Yoshiyuki Kuroda ': 327, ' Mark Jean ': 328, ' Taavi Vartia ': 329, " Joe D'Amato ": 330, ' Bhavik Thakore ': 331, ' Kad Merad ': 332, ' James Morrison ': 333, ' Aleksey Kozlov ': 334, ' Leo McCarey ': 335, ' Stuart Samuels ': 336, ' Deborah Chow ': 337, ' Keiichi Hara ': 338, ' Paul Sloane ': 339, ' Uri Zohar ': 340, ' Joseph L. Mankiewicz ': 341, ' Morgan Neville ': 342, ' Gail Harvey ': 343, ' Eric Chaikin ': 344, ' Pekka Lehto ': 345, ' Tod Browning ': 346, ' Steve Previn ': 347, ' John Herzfeld ': 348, ' Robert Siodmak ': 349, ' Pao-Shu Kao ': 350, ' Michael Curtiz ': 351, ' Marc Allégret ': 352, ' Steve Martino ': 353, ' Hana Makhmalbaf ': 354, ' Victor Duncan ': 355, ' Jean Bach ': 356, ' Michael Findlay ': 357, ' Stuart Rosenberg ': 358, ' Keoni Waxman ': 359, ' Jeff Tremaine ': 360, ' Walt Becker ': 361, ' Arlene Sanford ': 362, ' Sam Friedlander ': 363, ' Robert Arkless ': 364, ' Irving Pichel ': 365, ' Federico Veiroj ': 366, ' Richard Thorpe ': 367, ' Piotr Szulkin ': 368, ' Anthony Drazan ': 369, ' Stanley Tong ': 370, ' Toshiharu Ikeda ': 371, ' Cheh Chang ': 372, ' Martin Donovan ': 373, ' Tomasz Baginski ': 374, ' Denis Dercourt ': 375, ' Ezra Kemp ': 376, ' Heather Rae ': 377, ' Pontus Klänge ': 378, ' Mel Gibson ': 379, ' Richard Marquand ': 380, ' James Rouse ': 381, ' Thomas Bezucha ': 382, ' Hirokazu Koreeda ': 383, ' Henri Decoin ': 384, ' Dave Fleischer ': 385, ' Don Jones ': 386, ' Bill Leslie ': 387, ' Barney Platts-Mills ': 388, ' Craig Chester ': 389, ' Neil Jordan ': 390, ' John Carpenter ': 391, ' Tommy Wirkola ': 392, ' Hans Petter Moland ': 393, ' Robert Redford ': 394, ' Wim Wenders ': 395, ' Hee-il Leesong ': 396, ' Andrey Konchalovskiy ': 397, ' Gustav Möller ': 398, ' Bill Condon ': 399, ' Wiktor Grodecki ': 400, ' Beth McCarthy-Miller ': 401, ' Robert Z. Leonard ': 402, ' Osamu Dezaki ': 403, ' Shaka King ': 404, ' Eric Norris ': 405, ' Rohit Shetty ': 406, ' Arthur Ripley ': 407, ' Phil Roman ': 408, ' Imtiaz Ali ': 409, ' Richard Gale ': 410, ' Kinka Usher ': 411, ' Kris Boustedt ': 412, ' Armand Mastroianni ': 413, ' Wolfgang Büld ': 414, ' Dennis Dugan ': 415, ' Krzysztof Kieslowski ': 416, ' Grethe Bøe-Waal ': 417, ' Dino Risi ': 418, ' Paul Mazursky ': 419, ' Randall Wallace ': 420, ' Christian Petzold ': 421, ' Jonathan Glendening ': 422, ' William Wesley ': 423, ' Christian Carion ': 424, ' Gary Sinise ': 425, ' Sammo Kam-Bo Hung ': 426, ' Garry Marshall ': 427, ' Anthony Mann ': 428, ' William A. Seiter ': 429, ' Mike Binder ': 430, ' Nicholas Molinari ': 431, ' Burt Kennedy ': 432, ' Andrzej Wajda ': 433, ' Kiyoshi Kurosawa ': 434, ' Selçuk Aydemir ': 435, ' Carlo Carlei ': 436, ' Jung Bum-shik ': 437, ' Dee McLachlan ': 438, ' Mike Rohl ': 439, ' Jeff Tomsic ': 440, ' John Farrow ': 441, ' Georg Fenady ': 442, ' Katie Torpey ': 443, ' Lawrence Kasdan ': 444, ' Delmer Daves ': 445, ' Rowland V. Lee ': 446, ' Wolfgang Murnberger ': 447, ' Penn Jillette ': 448, ' Fabrizio De Angelis ': 449, ' Ray Yeung ': 450, ' Khushboo Ranka ': 451, ' Adam Simon ': 452, ' Sam Mendes ': 453, ' Nathan Juran ': 454, ' Cristian Mungiu ': 455, ' Franco Rossi ': 456, ' Tom McLoughlin ': 457, ' Danny Draven ': 458, ' Rasmus Heisterberg ': 459, ' Viktors Ritelis ': 460, ' David Hand ': 461, ' Karen Goodman ': 462, ' Karen Moncrieff ': 463, ' Michael Apted ': 464, ' Cyrus Frisch ': 465, ' Hayden J. Weal ': 466, ' Adam Curtis ': 467, ' Jeremi Mattern ': 468, ' Vincenzo Natali ': 469, ' José Padilha ': 470, ' Michael Feifer ': 471, ' Ewing Scott ': 472, ' Stanislav Rostotskiy ': 473, ' Mervyn LeRoy ': 474, ' Ferdinando Baldi ': 475, ' Gil Bettman ': 476, ' Mani Ratnam ': 477, ' Steno ': 478, ' Christian Duguay ': 479, ' Donald Petrie ': 480, ' Jack Cardiff ': 481, ' N. Linguswamy ': 482, ' Natalia Mirzoyan ': 483, ' Harvey Hart ': 484, ' Héctor Carré ': 485, ' Giuseppe Rosati ': 486, ' Harvey Glazer ': 487, ' Philippe Garrel ': 488, ' Sergio Leone ': 489, ' Richard Lanni ': 490, ' Toby Tobias ': 491, ' Charles F. Haas ': 492, ' James Ivory ': 493, ' Banjong Pisanthanakun ': 494, ' Jan Schütte ': 495, ' William Beaudine ': 496, ' Lars von Trier ': 497, ' Jacques Tourneur ': 498, ' Delbert Mann ': 499, ' Juraj Jakubisko ': 500, ' Harun Farocki ': 501, ' Greg Barker ': 502, ' Luigi Zampa ': 503, ' Kinji Fukasaku ': 504, ' Mohsen Makhmalbaf ': 505, ' Lev L. Spiro ': 506, ' Giuliano Montaldo ': 507, ' Charles Nichols ': 508, ' Edgar Wright ': 509, ' Zhanna Bekmambetova ': 510, ' Samuli Valkama ': 511, ' Jonás Cuarón ': 512, ' Blake Edwards ': 513, ' Mikael Salomon ': 514, ' George Sluizer ': 515, ' Felix Moeller ': 516, ' Oleg Assadulin ': 517, ' Jack Couffer ': 518, ' Ivan Aksenchuk ': 519, ' Tim Whelan ': 520, ' Alejandro Monteverde ': 521, ' Don Siegel ': 522, ' Fritz Lang ': 523, ' Leste Chen ': 524, ' Brian Trenchard-Smith ': 525, ' Christian Theede ': 526, ' Hamilton MacFadden ': 527, ' Stanley Tucci ': 528, ' Yasujirô Ozu ': 529, ' Damiano Damiani ': 530, ' Claude Binyon ': 531, ' Jerry Ciccoritti ': 532, ' Mohamed Diab ': 533, ' Eric-Emmanuel Schmitt ': 534, ' Giovanni Pastrone ': 535, ' Eloy de la Iglesia ': 536, ' Alessandro Santini ': 537, ' Jim Lounsbury ': 538, ' Pedro Amorim ': 539, ' George Sidney ': 540, ' Tomoharu Katsumata ': 541, ' Allan Deberton ': 542, ' Joël Séria ': 543, ' Hawley Pratt ': 544, ' Tatsushi Ômori ': 545, ' John Byrum ': 546, ' Paul Schneider ': 547, ' James Hart ': 548, ' Ross MacGibbon ': 549, ' Rachel Lee Goldenberg ': 550, ' Christopher Fitchett ': 551, ' Jon Favreau ': 552, ' Henry Hathaway ': 553, ' Peter Maris ': 554, ' Chris Hunt ': 555, ' Gordon Chan ': 556, ' Stephen Daldry ': 557, ' Georgiy Daneliya ': 558, ' Michael M. Scott ': 559, ' Indra Kumar ': 560, ' Justin Dec ': 561, ' Jeremy Gardner ': 562, ' Peter Strickland ': 563, ' David Leland ': 564, ' Carlos Osuna ': 565, ' Ulrike Grote ': 566, ' Paul Hoen ': 567, " Dan O'Bannon ": 568, ' Wes Ball ': 569, ' Timothy Woodward Jr. ': 570, ' W.S. Van Dyke ': 571, ' Joy N. Houck Jr. ': 572, ' Ivan Reitman ': 573, ' Kazuo Inoue ': 574, ' Vicente Villanueva ': 575, ' Alan J. Pakula ': 576, ' Jez Butterworth ': 577, ' James B. Harris ': 578, ' Sebastian Gutierrez ': 579, ' Neil Jones ': 580, ' David Helpern ': 581, ' Olivier Megaton ': 582, ' Seth Green ': 583, ' Luca Bercovici ': 584, ' Jens Hoffmann ': 585, ' John Simpson ': 586, ' Hamid Nematollah ': 587, ' Sanjay Leela Bhansali ': 588, ' Otto Preminger ': 589, ' Neill Blomkamp ': 590, ' Takeshi Furusawa ': 591, ' Douglas Schulze ': 592, ' Neil LaBute ': 593, ' Robert Rodriguez ': 594, ' Allison Anders ': 595, ' Jean-François Giré ': 596, ' Bob Schultz ': 597, ' Charlie Loventhal ': 598, ' Kevin Billington ': 599, ' Mario Van Peebles ': 600, ' Dominic Brigstocke ': 601, ' Mark A.Z. Dippé ': 602, ' Gabrielle Anwar ': 603, ' Steffi Kammerer ': 604, ' Yuliy Gusman ': 605, ' Scott Rodgers ': 606, ' Michael Dweck ': 607, ' Lansing C. Holden ': 608, ' Paul L. Stein ': 609, ' Nina Paley ': 610, ' Roddy Bogawa ': 611, ' Robert Hall ': 612, ' William K. Howard ': 613, ' Ridley Scott ': 614, ' Rod Lurie ': 615, ' Matthew Thompson ': 616, ' Bob Rafelson ': 617, ' Roger Spottiswoode ': 618, ' Andrés Kaiser ': 619, ' Mario Siciliano ': 620, ' Park Chan-wook ': 621, ' Ron Howard ': 622, ' Steven Soderbergh ': 623, ' Rob Williams ': 624, ' Scott Speer ': 625, ' Pietro Germi ': 626, ' William Victor Schotten ': 627, ' Fred M. Wilcox ': 628, ' Joan Chen ': 629, ' Stephen Traxler ': 630, ' Ali Samadi Ahadi ': 631, ' Daniel Schechter ': 632, ' Ralf Huettner ': 633, ' Svetlana Druzhinina ': 634, ' Wayne Blair ': 635, ' Sylvain White ': 636, ' Hakan Algül ': 637, ' Michael McCullers ': 638, ' Bradley Raymond ': 639, ' Suk-Yoon Kim ': 640, ' William A. Levey ': 641, ' Roberto Benigni ': 642, ' David Gleeson ': 643, ' Eben McGarr ': 644, ' Peter H. Hunt ': 645, ' Milorad Krstic ': 646, ' Robert Mandel ': 647, ' Curtis Hanson ': 648, ' Dennis Gansel ': 649, ' Luigi Comencini ': 650, ' Václav Kaslík ': 651, ' Seijun Suzuki ': 652, ' Pete Walker ': 653, ' Giancarlo Santi ': 654, ' Davis Doi ': 655, ' Andrew Marton ': 656, ' Luciano Onetti ': 657, ' Daniel Grou ': 658, ' James Foley ': 659, ' Raymond Martino ': 660, ' John Carr ': 661, ' Stephen Kogon ': 662, ' Thierry Binisti ': 663, ' Stephan Elliott ': 664, ' Anika Decker ': 665, ' Jonathan Hock ': 666, ' Fred F. Sears ': 667, ' Kevin Lima ': 668, ' Michael Winner ': 669, ' Sam Pillsbury ': 670, ' Ismael Rodríguez ': 671, ' Gren Wells ': 672, ' Sidney Sheldon ': 673, ' Kristine Peterson ': 674, ' Luis Buñuel ': 675, ' Adam Coleman Howard ': 676, ' Terence Young ': 677, ' Mick Jackson ': 678, ' George Siougas ': 679, ' Tariq Tapa ': 680, ' Stephanie Rothman ': 681, ' Jacques-Yves Cousteau ': 682, ' Sergio Garrone ': 683, ' Adam Shankman ': 684, ' Buster Keaton ': 685, ' John Ridley ': 686, ' Tom Long ': 687, ' Scott Hamilton Kennedy ': 688, ' Ron Scalpello ': 689, ' Jonnie Malachi ': 690, ' Roland Suso Richter ': 691, ' James Hale ': 692, ' Douglas Jackson ': 693, ' Jimmy Huston ': 694, ' Antonio Margheriti ': 695, ' Charles Robert Carner ': 696, ' Hideo Nakata ': 697, ' Rolf de Heer ': 698, ' Glenn Jordan ': 699, ' Artur Wiecek ': 700, ' René Féret ': 701, ' Will Bakke ': 702, ' Scott Rubin ': 703, ' William Malone ': 704, ' Philippe Lioret ': 705, ' Gabrielle Demeestere ': 706, ' Daisaku Kimura ': 707, ' Gus Van Sant ': 708, ' Marco Ferreri ': 709, ' Satyajit Ray ': 710, ' Olivier Ducastel ': 711, ' Eugene Marner ': 712, ' Jae-yeon Yun ': 713, ' Alessandro Blasetti ': 714, ' Paolo Virzì ': 715, ' Sang-woo Kim ': 716, ' Paul Weitz ': 717, ' Gerald Thomas ': 718, ' Eitan Reuven ': 719, ' Kiyoshi Sasabe ': 720, ' Dimitri Logothetis ': 721, ' Kevin Connor ': 722, ' Jeannot Szwarc ': 723, ' Tancred Ibsen ': 724, ' Tom Paton ': 725, ' Susannah Grant ': 726, ' Elite Zexer ': 727, ' Manuel Martín Cuenca ': 728, ' Robert Kane Pappas ': 729, ' Wallace Brothers ': 730, ' David VonAllmen ': 731, ' Harald Sicheritz ': 732, ' Whit Stillman ': 733, ' Mick Foley ': 734, ' Jayro Bustamante ': 735, ' Gerardo Herrero ': 736, ' Stanley Kwan ': 737, ' Lev Kuleshov ': 738, ' David Mamet ': 739, ' Christopher Blackmon ': 740, ' David Lee Madison ': 741, ' Mick Garris ': 742, ' Dominic Polcino ': 743, ' Ben Wheatley ': 744, ' Ted Kotcheff ': 745, ' Ken Hughes ': 746, ' Tony Bill ': 747, ' Jerry Jameson ': 748, ' Uwe Boll ': 749, ' Thomas Gulamerian ': 750, ' Vincente Minnelli ': 751, ' Jesse Pomeroy ': 752, ' Jan Hrebejk ': 753, ' Benjamin Andrews ': 754, ' Peter Howitt ': 755, ' Bradley Cox ': 756, ' John Hayes ': 757, ' Hella Joof ': 758, ' Robert Greenwald ': 759, ' John Lyde ': 760, ' Mark LaFleur ': 761, ' Sidney Lanfield ': 762, ' Michael Herz ': 763, ' Thierry Ragobert ': 764, ' Mark Hall ': 765, ' Lance Daly ': 766, ' Ted Post ': 767, ' Campbell Scott ': 768, ' Terry Hughes ': 769, ' H. Bruce Humberstone ': 770, ' Aleksi Salmenperä ': 771, ' Juan Luis Buñuel ': 772, ' José Luis Rugeles ': 773, ' Todd Bellanca ': 774, ' Hee-kon Park ': 775, ' John Brahm ': 776, ' Tarsem Singh ': 777, ' Maria Beatty ': 778, ' Salvatore Stabile ': 779, ' Roman Kachanov ': 780, ' Arna Selznick ': 781, ' Peeter Simm ': 782, ' Guillaume Nicloux ': 783, ' Nikolay Lebedev ': 784, ' Andrew Martin ': 785, ' Douglas Sirk ': 786, ' Jeffrey Johnson ': 787, ' Charlotte Purdy ': 788, ' William Dieterle ': 789, ' Keita Amemiya ': 790, ' Fernando Arrabal ': 791, ' David Gordon Green ': 792, ' Emmanuel Finkiel ': 793, ' Martin E. Johnson ': 794, ' Mikko Kouki ': 795, ' Peter R. Hunt ': 796, ' Chelsea Stardust ': 797, ' Michael Vejar ': 798, ' Burt Lancaster ': 799, ' Doris Dörrie ': 800, ' Juan Mora Catlett ': 801, ' Stuart Burge ': 802, ' G. Marthandan ': 803, ' Yung Chang ': 804, ' Anne De Salvo ': 805, ' Cirio H. Santiago ': 806, ' Tony Martin ': 807, ' Art Linson ': 808, ' Edward L. Cahn ': 809, ' Ergin Orbey ': 810, ' Tyler Perry ': 811, ' Karl Anders Holman ': 812, ' Woo-Ping Yuen ': 813, ' Vladimir Khotinenko ': 814, ' J.G. Quintel ': 815, ' J.S. Cardone ': 816, ' Joseph Losey ': 817, ' Howard E. Baker ': 818, ' Guy Nattiv ': 819, ' Niels Arden Oplev ':

In [228]:
Actors = pd.concat([result.Actor_1,result.Actor_2,result.Actor_3],ignore_index = True)
Actors_list = list(set(Actors))

vector_counter = 0
vectorized_actors = {}

for actor in Actors_list:
    vectorized_actors[actor] = vector_counter
    vector_counter += 1
    
print(len(vectorized_actors))

2586

In [229]:
result

,IMDBid,Release_Date,Country_of_Origin,Movie_Length,Director,Actor_1,Actor_2,Actor_3
0,0120381,"February 17, 1999 (Argentina)",United States,1 hour 32 minutes,Catherine Cyran,Kirsten Dunst,Zachery Ty Bryan,August Schellenberg
1,5208950,"January 26, 2018 (Poland)",United States,1 hour 50 minutes,Dimitri Logothetis,Alain Moussi,Sara Malakul Lane,Maxime Savaria
2,2364841,"October 4, 2013 (Brazil)",United States,1 hour 28 minutes,Brad Furman,Justin Timberlake,Ben Affleck,Gemma Arterton
3,2854926,"August 23, 2018 (Brazil)",United States,1 hour 40 minutes,Jeff Tomsic,Ed Helms,Lil Rel Howery,Jon Hamm
4,4397382,"October 16, 2015 (Sweden)",Sweden,1 hour 11 minutes,Pontus Klänge,Amanda Pajus,Lukas Holgersson,Tomas Norström
...,...,...,...,...,...,...,...,...
925,0310851,2002 (Canada),Canada,1 hour 30 minutes,Rodney Gibbons,Matt Frewer,Kenneth Welsh,Shawn Lawrence
926,1427241,"May 23, 2009 (Japan)",Japan,1 hour 58 minutes,Jun'ichi Mori,Ryo Kase,Masaki Okada,Fumiyo Kohinata
927,0110893,"June 1, 1994 (Czech Republic)",Czech Republic,1 hour 39 minutes,Zdenek Troska,Radek Valenta,Andrea Cerná,Yvetta Blanarovicová
928,0142239,"March 12, 1994 (Japan)",Japan,48 minutes,Shigeyasu Yamauchi,Masako Nozawa,Mayumi Tanaka,Takeshi Kusao
929,7227742,"July 17, 2017 (United States)",United States,1 hour 56 minutes,Derek Scott,Murda Pain,Lance Whittighton,Sino

In [231]:
countries_list = list(set(result.Country_of_Origin))

vector_counter = 0
vectorized_countries = {}

for country in countries_list:
    vectorized_countries[country] = vector_counter
    vector_counter += 1
    
print(len(vectorized_countries))

54

In [237]:
ratings_df = pd.read_csv(path + '/' + 'ratings.csv',dtype='str')
ratings_df

          userId movieId rating   timestamp
0              1     296    5.0  1147880044
1              1     306    3.5  1147868817
2              1     307    5.0  1147868828
3              1     665    5.0  1147878820
4              1     899    3.5  1147868510
...          ...     ...    ...         ...
25000090  162541   50872    4.5  1240953372
25000091  162541   55768    2.5  1240951998
25000092  162541   56176    2.0  1240950697
25000093  162541   58559    4.0  1240953434
25000094  162541   63876    5.0  1240952515

[25000095 rows x 4 columns]

# Loading Data

In [ ]:
PROJECT = "filmaholic-398017"
DATASET = "filmaholic"
cache_path = Path('raw_data/')

In [ ]:
tables_to_query = ['actors', 'directors', 'country', 'ratings', 'like_dislike_tags','movies']
dfs = {}

In [ ]:
for table in tables_to_query:

    file_cache_path = cache_path.joinpath(f"{table}.csv")

    if file_cache_path.is_file():
        dfs[table] = pd.read_csv(file_cache_path, dtype='str')

        print(f"Table {table} loaded from cache")

    else:
        pass

In [ ]:
selected_ids = list(dfs['like_dislike_tags'].userId)

In [ ]:
merged = dfs['ratings'].merge(dfs['movies'], on='movieId', how='left')

# Processing

## Directors

In [ ]:
raw_directors = dfs['directors'].copy()
# raw_tags.userId = raw_tags.userId.astype('string')
# raw_tags.movieId = raw_tags.movieId.astype('string')
directors = raw_directors[raw_directors.userId.isin(user_list)]
directors = directors.drop('timestamp', axis=1).dropna()

In [ ]:
raw_movies = dfs['movies'].copy()
# raw_movies.movieId = raw_movies.movieId.astype('string')
movies = raw_movies[raw_movies.movieId.isin(movies_list)]

In [ ]:
raw_ratings = dfs['ratings'].copy()
# raw_ratings.movieId = raw_ratings.movieId.astype('string')
# raw_ratings.rating = raw_ratings.rating.astype('float')
ratings = raw_ratings[raw_ratings.userId.isin(user_list)]

In [ ]:
directors_popular_movies = tags[tags.movieId.isin(movies_list)]
directors_unique_users = list(tags_popular_movies.drop_duplicates('userId').userId)

In [ ]:
common_actors_df = tags_popular_movies.groupby(['tag']).count().sort_values('userId', ascending= False).copy().drop('movieId', axis= 1).reset_index()
common_tags_df = common_tags_df[common_tags_df.userId >= 20]
common_tags_df.to_csv('raw_data/common_tags.csv', index = False)

In [ ]:
# CELL 8

# Creating a new DF that contains the most common tags for each movie ("movieId"):

## This will create a new DF for each movie and will store this file since there is no easy storage method for this task
### Storage will be in the "data" folder under the "movie_tags" subfolder:

if os.path.exists('data/movie_directors/') != True: # Creating movie_tags subfolder
    os.mkdir('data/movie_directors/')

## Creating a copy of tags_df_mod and dropping userID:
tags_df_mod = pd.read_csv('data/tags.csv')

tags_df_no_user = tags_df_mod.copy().drop('userId', axis= 1)

## Obtaining a list of all movieId with tags:
### !!!! The set() function does not put the list in perfect order. Some of the IDs are out-of-place.
movieId_list = list(set(tags_df_no_user.movieId))

for movieId in movieId_list:
    df_select = tags_df_no_user[tags_df_no_user.movieId == movieId].copy().drop('movieId', axis= 1)

    df_select['COUNT'] = 1

    df_select_group = df_select.groupby(['tag']).count()

    df_select_group = df_select_group.sort_values(by=['COUNT'], ascending= False).reset_index()

    df_select_group.to_csv('data/movie_directors/' + str(movieId) + '.csv', index = False)

In [ ]:
# ratings_df_removed = pd.read_csv('data/ratings_df_last_liked_movie_removed.csv')

# user_list = list(set(ratings_df_removed.userId))

# like_dislike_directors = pd.DataFrame()

# for user in user_list:

#     temp_ratings_df = ratings_df_removed[ratings_df_removed.userId == user]
#     like_directors_df = pd.DataFrame()
#     dislike_directors_df = pd.DataFrame()

In [233]:
#     for index, row in temp_ratings_df.iterrows():  ## selecting favorite and least favorite directors for each user
#         try: ### This is to check if the directors exist
#             if row.rating >= 4: # Like
#                 temp_movie_df = pd.read_csv('data/movie_directors/{}.csv'.format(str(int(row.movieId)))) ## This oddly turns the movieId into a float, most likely to match the other data types in the selected series
#                 if len(like_directors_df) == 0:
#                     like_directors_df = temp_movie_df

#                 else:
#                     like_directors_df = pd.concat([like_directors_df, temp_movie_df], ignore_index= True)

#             else:
#                 temp_movie_df = pd.read_csv('data/movie_directors/{}.csv'.format(str(int(row.movieId))))

#                 if len(like_directors_df) == 0:
#                     dislike_directors_df = temp_movie_df

#                 else:
#                     dislike_directors_df = pd.concat([dislike_directors_df, temp_movie_df], ignore_index= True)
#         except Exception:
#             pass

In [ ]:
#     ## Counting all directors
#     try:  ### This is to check if the user has movies they've liked or disliked. Users who only have liked movies will be skipped (example: userId 173)
#         like_directors_list = list(like_directors_df.director)
#         dislike_directors_list = list(dislike_directors_df.director)
#     except Exception:
#         continue

In [ ]:
#     like_dict = {}
#     dislike_dict = {}

#     for director in like_directors_list:
#         like_dict[director] = like_directors_list.count(director) * -1  ### This is multiple by -1 to convert it to a negative numerical count for the sorting that will be done next

#     for director in dislike_directors_list:
#         dislike_dict[director] = dislike_directors_list.count(director) * -1

In [ ]:
#     like_directors_counted = sorted(like_dict, key= lambda director: like_dict[director])  ## Returns a list of the tags
#     dislike_directors_counted = sorted(dislike_dict, key= lambda director: dislike_dict[director])

#     ## Converting the tags to vectorized tags but only for the first 50 tags from the like and dislike tags counted lists
#     like_directors_vectorized = []
#     dislike_directors_vectorized = []

#     if len(like_directors_counted) < 50:  ## Checking to make sure there is 50 tags in the counted lists
#         num_like_directors = len(like_directors_counted)
#     else:
#         num_like_directors = 50

#     if len(dislike_directors_counted) < 50:
#         num_dislike_directors = len(like_directors_counted)
#     else:
#         num_dislike_directors = 50

#     for director in like_directors_counted[:num_like_directors]:
#         try:  ### The tag might not exist in the vectorized dictionary
#             director_vector = vectorized_dict[director]
#             like_directors_vectorized.append(director_vector)
#         except Exception:
#             pass

#     for director in dislike_directors_counted[:num_dislike_directors]:
#         try:
#             director_vector = vectorized_dict[director]
#             dislike_director_vectorized.append(director_vector)
#         except Exception:
#             pass

In [240]:
'''THINK ABOUT THIS ONE(IF NUMBER OF DIRECTORS IS APPROPRIATE)'''
#     if len(like_directors_vectorized) < 20 or len(dislike_directors_vectorized) < 20:
#         continue  ## If any of the two are not 20 directors in length, then the user will be skipped

'THINK ABOUT THIS ONE(IF NUMBER OF DIRECTORS IS APPROPRIATE)'

In [ ]:
'''THINK ABOUT THIS ONE(IF NUMBER OF DIRECTORS IS APPROPRIATE)'''
#     ## Obtaining the most liked and disliked directors, 20 director each, and adding it to like_dislike_directors:
#     like_dislike_dict = {}

#     like_dislike_dict['userId'] = user

#     for x in range(20):
#         like_dislike_dict['LIKE_' + str(x)] = like_directors_vectorized[x]
#         like_dislike_dict['DISLIKE_' + str(x)] = dislike_directors_vectorized[x]

#     concat_df = pd.DataFrame(like_dislike_dict, index=[0])

#     if len(like_dislike_directors) == 0:
#         like_dislike_directors = concat_df

#     else:
#         like_dislike_directors = pd.concat([like_dislike_directors,concat_df], ignore_index= True)

In [ ]:
# like_dislike_directors = like_dislike_directors.astype('int64')
# like_dislike_directors.to_csv('data/final/like_dislike_directors.csv', index = False)

## Actors

In [ ]:
# ratings_df_removed = pd.read_csv('data/ratings_df_last_liked_movie_removed.csv')

# user_list = list(set(ratings_df_removed.userId))

# like_dislike_actors = pd.DataFrame()

# for user in user_list:

#     temp_ratings_df = ratings_df_removed[ratings_df_removed.userId == user]
#     like_actors_df = pd.DataFrame()
#     dislike_actors_df = pd.DataFrame()

In [ ]:
#     for index, row in temp_ratings_df.iterrows():  ## selecting favorite and least favorite actors for each user
#         try:
#             if row.rating >= 4: # Like
#                 temp_movie_df = pd.read_csv('data/movie_actors/{}.csv'.format(str(int(row.movieId)))) ## This oddly turns the movieId into a float, most likely to match the other data types in the selected series
#                 if len(like_actors_df) == 0:
#                     like_actors_df = temp_movie_df

#                 else:
#                     like_actors_df = pd.concat([like_actors_df, temp_movie_df], ignore_index= True)

#             else:
#                 temp_movie_df = pd.read_csv('data/movie_actors/{}.csv'.format(str(int(row.movieId))))

#                 if len(like_actors_df) == 0:
#                     dislike_actors_df = temp_movie_df

#                 else:
#                     dislike_actors_df = pd.concat([dislike_actors_df, temp_movie_df], ignore_index= True)
#         except Exception:
#             pass

In [ ]:
#     ## Counting all actors
#     try:  ### This is to check if the user has movies they've liked or disliked. Users who only have liked movies will be skipped (example: userId 173)
#         like_actors_list = list(like_actors_df.actor)
#         dislike_actors_list = list(dislike_actors_df.actor)
#     except Exception:
#         continueactors

In [ ]:
#     like_dict = {}
#     dislike_dict = {}

#     for actor in like_actors_list:
#         like_dict[actor] = like_actors_list.count(actor) * -1  ### This is multiple by -1 to convert it to a negative numerical count for the sorting that will be done next

#     for actor in dislike_actors_list:
#         dislike_dict[actor] = dislike_actors_list.count(actor) * -1

In [ ]:
#     like_actors_counted = sorted(like_dict, key= lambda actor: like_dict[actor])  ## Returns a list of the tags
#     dislike_actors_counted = sorted(dislike_dict, key= lambda actor: dislike_dict[actor])

#     ## Converting the tags to vectorized tags but only for the first 50 tags from the like and dislike tags counted lists
#     like_actors_vectorized = []
#     dislike_actors_vectorized = []

#     if len(like_actors_counted) < 50:  ## Checking to make sure there is 50 tags in the counted lists
#         num_like_actors = len(like_actors_counted)
#     else:
#         num_like_actors = 50

#     if len(dislike_actors_counted) < 50:
#         num_dislike_actors = len(like_actors_counted)
#     else:
#         num_dislike_actors = 50

#     for actor in like_actors_counted[:num_like_actors]:
#         try:  ### The tag might not exist in the vectorized dictionary
#             actor_vector = vectorized_dict[actor]
#             like_actors_vectorized.append(actor_vector)
#         except Exception:
#             pass

#     for actor in dislike_actors_counted[:num_dislike_actors]:
#         try:
#             actor_vector = vectorized_dict[actor]
#             dislike_actors_vectorized.append(actor_vector)
#         except Exception:
#             pass

In [ ]:
#     if len(like_actors_vectorized) < 20 or len(dislike_actors_vectorized) < 20:
#         continue  ## If any of the two are not 20 tags in length, then the user will be skipped

In [ ]:
'''THINK ABOUT THIS ONE(IF NUMBER OF TAGS IS APPROPRIATE)'''
#     ## Obtaining the most liked and disliked actors, 20 tags each, and adding it to like_dislike_actors:
#     like_dislike_dict = {}

#     like_dislike_dict['userId'] = user

#     for x in range(20):
#         like_dislike_dict['LIKE_' + str(x)] = like_actors_vectorized[x]
#         like_dislike_dict['DISLIKE_' + str(x)] = dislike_actors_vectorized[x]

#     concat_df = pd.DataFrame(like_dislike_dict, index=[0])

#     if len(like_dislike_actors) == 0:
#         like_dislike_actors = concat_df

#     else:
#         like_dislike_actors = pd.concat([like_dislike_actors,concat_df], ignore_index= True)

In [ ]:
# like_dislike_actors = like_dislike_actors.astype('int64')
# like_dislike_actors.to_csv('data/final/like_dislike_actors.csv', index = False)

## Country of Origin

In [241]:
# ratings_df_removed = pd.read_csv('data/ratings_df_last_liked_movie_removed.csv')

# user_list = list(set(ratings_df_removed.userId))

# like_dislike_countries = pd.DataFrame()

# for user in user_list:

#     temp_ratings_df = ratings_df_removed[ratings_df_removed.userId == user]
#     like_countries_df = pd.DataFrame()
#     dislike_countries_df = pd.DataFrame()

In [ ]:
#     for index, row in temp_ratings_df.iterrows():  ## selecting favorite and least favorite countries for each user
#         try:
#             if row.rating >= 4: # Like
#                 temp_movie_df = pd.read_csv('data/movie_countries/{}.csv'.format(str(int(row.movieId)))) ## This oddly turns the movieId into a float, most likely to match the other data types in the selected series
#                 if len(like_countries_df) == 0:
#                     like_countries_df = temp_movie_df

#                 else:
#                     like_countries_df = pd.concat([like_countries_df, temp_movie_df], ignore_index= True)

#             else:
#                 temp_movie_df = pd.read_csv('data/movie_countries/{}.csv'.format(str(int(row.movieId))))

#                 if len(like_countries_df) == 0:
#                     dislike_countries_df = temp_movie_df

#                 else:
#                     dislike_countries_df = pd.concat([dislike_countries_df, temp_movie_df], ignore_index= True)
#         except Exception:
#             pass

In [ ]:
#     ## Counting all countries
#     try:  ### This is to check if the user has movies they've liked or disliked. Users who only have liked movies will be skipped (example: userId 173)
#         like_countries_list = list(like_countries_df.country)
#         dislike_countries_list = list(dislike_countries_df.country)
#     except Exception:
#         continue

In [ ]:
#     like_dict = {}
#     dislike_dict = {}

#     for country in like_countries_list:
#         like_dict[country] = like_countries_list.count(country) * -1  ### This is multiple by -1 to convert it to a negative numerical count for the sorting that will be done next

#     for country in dislike_countries_list:
#         dislike_dict[country] = dislike_countries_list.count(country) * -1

In [ ]:
#     like_countries_counted = sorted(like_dict, key= lambda country: like_dict[country])  ## Returns a list of the tags
#     dislike_countries_counted = sorted(dislike_dict, key= lambda country: dislike_dict[country])

#     ## Converting the tags to vectorized tags but only for the first 50 tags from the like and dislike tags counted lists
#     like_countries_vectorized = []
#     dislike_countries_vectorized = []

#     if len(like_countries_counted) < 50:  ## Checking to make sure there is 50 tags in the counted lists
#         num_like_countries = len(like_countries_counted)
#     else:
#         num_like_countries = 50

#     if len(dislike_countries_counted) < 50:
#         num_dislike_countries = len(like_countries_counted)
#     else:
#         num_dislike_countries = 50

#     for country in like_countries_counted[:num_like_countries]:
#         try:  ### The tag might not exist in the vectorized dictionary
#             country_vector = vectorized_dict[country]
#             like_countries_vectorized.append(country_vector)
#         except Exception:
#             pass

#     for country in dislike_countries_counted[:num_dislike_countries]:
#         try:
#             country_vector = vectorized_dict[country]
#             dislike_countries_vectorized.append(country_vector)
#         except Exception:
#             pass

In [ ]:
#     if len(like_countries_vectorized) < 20 or len(dislike_countries_vectorized) < 20:
#         continue  ## If any of the two are not 20 tags in length, then the user will be skipped

In [ ]:
'''THINK ABOUT THIS ONE(IF NUMBER OF TAGS IS APPROPRIATE)'''
#     ## Obtaining the most liked and disliked countries, 20 tags each, and adding it to like_dislike_countrie:
#     like_dislike_dict = {}

#     like_dislike_dict['userId'] = user

#     for x in range(20):
#         like_dislike_dict['LIKE_' + str(x)] = like_countries_vectorized[x]
#         like_dislike_dict['DISLIKE_' + str(x)] = dislike_countries_vectorized[x]

#     concat_df = pd.DataFrame(like_dislike_dict, index=[0])

#     if len(like_dislike_countries) == 0:
#         like_dislike_countries = concat_df

#     else:
#         like_dislike_countries = pd.concat([like_dislike_countries,concat_df], ignore_index= True)

In [ ]:
# like_dislike_countries = like_dislike_countries.astype('int64')
# like_dislike_countries.to_csv('data/final/like_dislike_countries.csv', index = False)